# [√]需要手动修改 [-]不推荐修改 [※]可选项，不影响系统运行

# ===================================================
# [√] 应用钥匙
# ---------------------------------------------------
# 应用鉴权
# ===================================================
APP_ID: ""
APP_SECRET: ""

# ===================================================
# [√] webhook uuid
# ---------------------------------------------------
# 用于向内部群组响应消息
# ===================================================
WEBHOOK_UUID: ""
CHAT_ID: ""

# ===================================================
# [※] 企业内建应用的可访问性令牌
# ===================================================
TENANT_ACCESS_TOKEN: ""

# ===================================================
# [-] Sentinel settings
# ---------------------------------------------------
# 用于向内部群组响应消息
# ===================================================
