name: hCaptcha Sentinel

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
      - ".deepsource.toml"
  workflow_dispatch:
#  schedule:
#    - cron: "10 23 * * 4,5"

jobs:
  setup:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OWNER: ${{ secrets.GITHUB_OWNER }}
      GITHUB_REPO: ${{ secrets.GITHUB_REPO }}
      FAKE_HASH: "Automated deployment @ $(date '+%Y-%m-%d %H:%M:%S') Asia/Shanghai"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip' # caching pip dependencies
    - name: 安装依赖
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        # pip install -r requirements.txt
        # playwright install firefox
        # playwright install-deps firefox
    - name: sentinel
      run: |
        python3 sentinel.py
    - name: Setup GIT user
      uses: fregante/setup-git-user@v1
    - name: 缓存身份令牌
      run: |
        echo "${{ env.FAKE_HASH }}" > _token
        git add .
        git commit -m "${{ env.FAKE_HASH }}" 
        git push -f